apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  replicas: 1
  serviceName: postgresql
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:13
        env:
        - name: POSTGRES_DB
          value: myapp_production
        - name: POSTGRES_USER
          value: myapp_user
        - name: POSTGRES_PASSWORD
          value: myapp_password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-app
        image: < my-rails-app>
        env:
        - name: RAILS_ENV
          value: production
        - name: DATABASE_URL
          value: postgresql://myapp_user:myapp_password@postgresql/myapp_production
        ports:
        - containerPort: 3000
